### ISSUE TITLE
please add to community bundle :)

### ISSUE THREAD

**Issue by ladyada** [jimbobbennett/CircuitPython_CustomVision#1]
https://github.com/adafruit/CircuitPython_Community_Bundle

this way people will know it exists :D

**Comment by jimbobbennett** [comment]
Yup, once it’s ready I’ll add it. Just got to add more documentation and samples and it’ll be ready to add.

**Comment by jimbobbennett** [comment]
Done! https://github.com/adafruit/CircuitPython_Community_Bundle/pull/36
